# Default values for ingress-example.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
colors:
  - red
  - orange
  - yellow
  - blue

defaultServicePort: 8080

nginxDeployments:
  - name: base
  - name: red
  - name: orange
  - name: yellow

nginxRunAsUser: 65534

services:
  nginx-base:
    serviceName: "nginx-base"
    prefix: "/"
    keepPrefix: true
  nginx-red:
    serviceName: "nginx-red"
    prefix: "/red"
  nginx-orange:
    serviceName: "nginx-orange"
    prefix: "/orange"
  nginx-yellow:
    serviceName: "nginx-yellow"
    prefix: "/yellow"
  echoserver:
    serviceName: "echoserver"
    prefix: "/echo"
    servicePort: 8090

ingress:
  enabled: true
  controller: traefik
  #controller: nginx
  #controller: kubernetes-nginx
  #controller: haproxy-openshift
  #controller: dummy
  host: ingress-example.laserschwert.io
  tls:
    - hosts:
        - ingress-example.laserschwert.io
      secretName: laserschwert-io-tls       # secret w/ TLS certificate
