apiVersion: v1
kind: ConfigMap
metadata:
  name: html-base-cm
  labels:
    {{- include "ingress-example.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>5 Squares</title>
        <style type="text/css">
            .square {
                width: 100px;
                height: 100px;
                margin: 20px;
                float: left;
                cursor: pointer;
            }
            .red { background-color: red; }
            .green { background-color: green; }
            .blue { background-color: blue; color: white }
            .black { background-color: black; color: white }
        </style>
    </head>
    <body>
    <div class="square red" onclick="window.location.href='/red'">RED</div>
    <div class="square green" onclick="window.location.href='/green'">GREEN</div>
    <div class="square blue" onclick="window.location.href='/blue'">BLUE</div>
    <div class="square black" onclick="window.location.href='/echo'">ECHO</div>
    <div class="square black" onclick="window.location.href='/local.html'">LOCAL</div>
    </body>
    </html>
  local.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Local Page</title>
    </head>
    <body>
    <h1>Hello from Base Deployment!</h1>
    </body>
    </html>
