apiVersion: v1
kind: ConfigMap
metadata:
  name: html-base-cm
  labels:
    {{- include "ingress-example.labels" . | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>5 Squares</title>
        <style>
            .square {
                width: 100px;
                height: 100px;
                margin: 20px;
                float: left;
                cursor: pointer;
                display: grid;
                align-items: center;
                justify-items: center;
                font-family: Ubuntu, sans-serif;
            }
            .red { background-color: red; }
            .orange { background-color: orange; }
            .yellow { background-color: yellow }
            .green { background-color: green; color: white }
            .blue { background-color: blue; color: white }
        </style>
    </head>
    <body>
    <div class="square red" onclick="window.location.href='/red'">RED</div>
    <div class="square orange" onclick="window.location.href='/orange'">ORANGE</div>
    <div class="square yellow" onclick="window.location.href='/yellow'">YELLOW</div>
    <div class="square green" onclick="window.location.href='/echo'">ECHO</div>
    <div class="square blue" onclick="window.location.href='/base-blue'">LOCAL</div>
    </body>
    </html>
