{{- range .Values.colors }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-{{ . }}-cm
  labels:
    {{- include "ingress-example.labels" $ | nindent 4 }}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>{{ . | camelcase }} Page</title>
        <style>
            h1 {
                text-align: center;
                background: {{ . }};
                color: {{ if eq . "yellow" }}black{{ else }}white{{ end }};
                font-family: Ubuntu, sans-serif;
            }
        </style>
    </head>
    <body>
    <h1>Hello from {{ . | camelcase }} Deployment!</h1>
    </body>
    </html>
{{- end }}
