{{- range .Values.nginxDeployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-{{ .name }}
  labels:
    {{- include "ingress-example.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx-{{ .name }}
  template:
    metadata:
      labels:
        run: nginx-{{ .name }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.1-alpine3.17
          ports:
            - name: http
              containerPort: {{ $.Values.defaultServicePort }}
          volumeMounts:
            - name: config-volume
              mountPath: "/usr/share/nginx/html"
            - name: nginx-conf-volume
              mountPath: "/etc/nginx/nginx.conf"
              subPath: nginx.conf
            - name: nginx-tmp
              mountPath: "/tmp"
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            {{- if not (empty $.Values.nginxRunAsUser) }}
            runAsUser: {{ $.Values.nginxRunAsUser }}
            {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: html-{{ .name }}-cm
        - name: nginx-conf-volume
          configMap:
            name: nginx-conf
        - name: nginx-tmp
          emptyDir: {}
{{- end }}
