apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    {{- include "ingress-example.labels" . | nindent 4 }}
data:
  nginx.conf: |
    # Based on https://www.nginx.com/resources/wiki/start/topics/examples/full/#nginx-conf
    # user              www www;  ## Default: nobody

    worker_processes  auto;

    error_log         /var/log/nginx/error.log notice;
    pid               /tmp/nginx.pid;

    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
        log_format    main '$remote_addr - $remote_user [$time_local] '
                           '"$request" $status  $body_bytes_sent "$http_referer" '
                           '"$http_user_agent" "$http_x_forwarded_for"';
        access_log    /var/log/nginx/access.log main;
        add_header    X-Frame-Options SAMEORIGIN;

        client_body_temp_path  /tmp/client_temp 1 2;
        proxy_temp_path        /tmp/proxy_temp 1 2;
        fastcgi_temp_path      /tmp/fastcgi_temp 1 2;
        scgi_temp_path         /tmp/scgi_temp 1 2;
        uwsgi_temp_path        /tmp/uwsgi_temp 1 2;

        sendfile           on;
        tcp_nopush         on;
        tcp_nodelay        off;
        gzip               on;
        gzip_http_version  1.0;
        gzip_comp_level    2;
        gzip_proxied       any;
        gzip_types         text/plain text/css application/javascript text/xml application/xml+rss;
        keepalive_timeout  65;
        ssl_protocols      TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers        HIGH:!aNULL:!MD5;
        client_max_body_size 80M;
        server_tokens off;

        absolute_redirect  off;
        port_in_redirect   off;

        server {
            listen       {{ .Values.servicePort | default 8080 }};
            server_name  localhost;
        
            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }
        
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    }

