{{- range $key, $value := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    {{- include "ingress-example.labels" $ | nindent 4 }}
spec:
  selector:
    run: {{ $key }}
  ports:
    - port: {{ $value.servicePort | default $.Values.defaultServicePort }}
      targetPort: http
      name: http
{{- end }}
